services:
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
    restart: unless-stopped
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672" # Porta padrão para a comunicação AMQP
      - "15672:15672" # Porta para a interface de gerenciamento web
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: subscription_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  redis:
    image: redis:6.2-alpine
    container_name: weather-bff-redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      # Mapeia um volume para persistir os dados do Redis
      - redis-data:/data
    command: redis-server --appendonly yes

volumes:
  db-data:
  rabbitmq_data:
  redis-data:
    driver: local
