services:
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - weather-network

  weather-subscription:
    build:
      context: ./weather-subscription-service
      dockerfile: Dockerfile
    container_name: weather-subscription-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=local
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - weather-network
  # weather-bff:
  #   build:
  #     context: ./weather-bff
  #     dockerfile: Dockerfile
  #   container_name: weather-bff
  #   ports:
  #     - "8082:8082" # Porta para sua aplicação BFF
  #   environment:
  #     - SPRING_PROFILES_ACTIVE=local
  #   restart: unless-stopped
  #   depends_on:
  #     - rabbitmq
  #     - redis
  #   networks:
  #     - weather-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672" # Porta padrão para a comunicação AMQP
      - "15672:15672" # Porta para a interface de gerenciamento web
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - weather-network

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: weather_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - weather-network

  redis:
    image: redis:6.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - weather-network

volumes:
  db-data:
  rabbitmq_data:
  redis-data:
    driver: local

networks:
  weather-network:
    driver: bridge
